name: Build Linux Executables

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]
        include:
          - os: ubuntu-22.04
            platform: ubuntu-22.04
          - os: ubuntu-24.04
            platform: ubuntu-24.04
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-pip \
            build-essential \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Project Dependencies
        run: |
          uv sync --all-extras
          uv pip install pyinstaller

      - name: Build with PyInstaller (CLI)
        run: |
          # 创建启动脚本避免相对导入问题
          cat > run_aipy.py << 'EOF'
          import sys
          from aipyapp.__main__ import main
          if __name__ == '__main__':
              sys.exit(main())
          EOF
          
          uv run pyinstaller \
            --onefile \
            --name aipy-linux-${{ matrix.platform }} \
            --console \
            --hidden-import aipyapp \
            --hidden-import anthropic \
            --hidden-import openai \
            --hidden-import pandas \
            --hidden-import fastapi \
            --hidden-import rich \
            --hidden-import prompt_toolkit \
            --hidden-import term_image \
            --hidden-import qrcode \
            --hidden-import loguru \
            --hidden-import questionary \
            --hidden-import dynaconf \
            --hidden-import beautifulsoup4 \
            --hidden-import mcp \
            --collect-all aipyapp \
            run_aipy.py

      - name: Test Executable
        run: |
          ./dist/aipy-linux-${{ matrix.platform }} --version || echo "Version check complete"
          ./dist/aipy-linux-${{ matrix.platform }} --help

      - name: Package Executable
        run: |
          cd dist
          tar -czf aipy-linux-${{ matrix.platform }}.tar.gz aipy-linux-${{ matrix.platform }}
          sha256sum aipy-linux-${{ matrix.platform }}.tar.gz > aipy-linux-${{ matrix.platform }}.tar.gz.sha256

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aipy-linux-${{ matrix.platform }}
          path: |
            dist/aipy-linux-${{ matrix.platform }}.tar.gz
            dist/aipy-linux-${{ matrix.platform }}.tar.gz.sha256

      - name: Upload to GitHub Releases
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/aipy-linux-${{ matrix.platform }}.tar.gz
            dist/aipy-linux-${{ matrix.platform }}.tar.gz.sha256
          token: ${{ secrets.GITHUB_TOKEN }}

  build-appimage:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-pip \
            build-essential \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev \
            fuse \
            libfuse2 \
            file \
            wget

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          uv sync --all-extras
          uv pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          # 创建启动脚本
          cat > run_aipy.py << 'EOF'
          import sys
          from aipyapp.__main__ import main
          if __name__ == '__main__':
              sys.exit(main())
          EOF
          
          # 构建单文件可执行
          uv run pyinstaller \
            --onefile \
            --name aipy \
            --console \
            --hidden-import aipyapp \
            --hidden-import anthropic \
            --hidden-import openai \
            --hidden-import pandas \
            --hidden-import fastapi \
            --hidden-import rich \
            --hidden-import prompt_toolkit \
            --hidden-import term_image \
            --hidden-import qrcode \
            --hidden-import loguru \
            --hidden-import questionary \
            --hidden-import dynaconf \
            --hidden-import beautifulsoup4 \
            --hidden-import mcp \
            --collect-all aipyapp \
            run_aipy.py

      - name: Download appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Create AppImage Structure
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/applications
          mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
          
          # 复制可执行文件
          cp dist/aipy AppDir/usr/bin/
          
          # 创建 desktop 文件
          cat > AppDir/usr/share/applications/aipy.desktop << 'EOF'
          [Desktop Entry]
          Type=Application
          Name=AIPy
          Exec=aipy
          Icon=aipy
          Categories=Utility;Development;
          Terminal=true
          EOF
          
          # 创建 AppRun
          cat > AppDir/AppRun << 'EOF'
          #!/bin/bash
          SELF=$(readlink -f "$0")
          HERE=${SELF%/*}
          export PATH="${HERE}/usr/bin:${PATH}"
          exec "${HERE}/usr/bin/aipy" "$@"
          EOF
          chmod +x AppDir/AppRun

      - name: Build AppImage
        run: |
          # Extract appimagetool for CI environment (no FUSE)
          ./appimagetool-x86_64.AppImage --appimage-extract
          
          # Build AppImage
          ARCH=x86_64 squashfs-root/AppRun AppDir aipy-x86_64.AppImage
          chmod +x aipy-x86_64.AppImage
          sha256sum aipy-x86_64.AppImage > aipy-x86_64.AppImage.sha256
          
          # Check file size
          ls -lh aipy-x86_64.AppImage

      - name: Test AppImage
        run: |
          ./aipy-x86_64.AppImage --version || echo "AppImage test complete"
          ./aipy-x86_64.AppImage --help

      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aipy-appimage
          path: |
            aipy-x86_64.AppImage
            aipy-x86_64.AppImage.sha256

      - name: Upload AppImage to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            aipy-x86_64.AppImage
            aipy-x86_64.AppImage.sha256
          token: ${{ secrets.GITHUB_TOKEN }}

  build-rpm-deb:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ruby \
            ruby-dev \
            rubygems \
            rpm \
            build-essential
          sudo gem install --no-document fpm

      - name: Install Project
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev \
            python3-pip \
            build-essential \
            zlib1g-dev \
            libjpeg-dev \
            libpng-dev \
            libfreetype6-dev
          
          uv sync --all-extras
          uv pip install pyinstaller
          uv build

      - name: Build PyInstaller Executable for Packaging
        run: |
          # 创建启动脚本
          cat > run_aipy.py << 'EOF'
          import sys
          from aipyapp.__main__ import main
          if __name__ == '__main__':
              sys.exit(main())
          EOF
          
          # 构建单文件可执行
          uv run pyinstaller \
            --onefile \
            --name aipy \
            --console \
            --hidden-import aipyapp \
            --hidden-import anthropic \
            --hidden-import openai \
            --hidden-import pandas \
            --hidden-import fastapi \
            --hidden-import rich \
            --hidden-import prompt_toolkit \
            --hidden-import term_image \
            --hidden-import qrcode \
            --hidden-import loguru \
            --hidden-import questionary \
            --hidden-import dynaconf \
            --hidden-import beautifulsoup4 \
            --hidden-import mcp \
            --collect-all aipyapp \
            run_aipy.py

      - name: Create DEB Package
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/usr/share/applications
          mkdir -p package/usr/share/doc/aipyapp
          
          # 使用 PyInstaller 生成的单文件可执行
          cp dist/aipy package/usr/local/bin/aipy
          chmod +x package/usr/local/bin/aipy
          
          # 获取版本号
          VERSION=$(uv run python -c "import aipyapp; print(aipyapp.__version__)" 2>/dev/null || echo "0.3.0")
          echo "Package version: $VERSION"
          
          # 测试可执行文件
          echo "Testing executable..."
          package/usr/local/bin/aipy --version || echo "Version check complete"
          
          # Create .deb
          fpm -s dir -t deb \
            -n aipyapp \
            -v "$VERSION" \
            --description "AI-Powered Python & Python-Powered AI (standalone executable)" \
            --url "https://github.com/knownsec/aipyapp" \
            --maintainer "ntbowen <ntbowen@users.noreply.github.com>" \
            --license "Apache-2.0" \
            -C package \
            usr/local/bin/aipy=/usr/local/bin/aipy

      - name: Create RPM Package
        run: |
          # 获取版本号
          VERSION=$(uv run python -c "import aipyapp; print(aipyapp.__version__)" 2>/dev/null || echo "0.3.0")
          
          fpm -s dir -t rpm \
            -n aipyapp \
            -v "$VERSION" \
            --description "AI-Powered Python & Python-Powered AI" \
            --url "https://github.com/knownsec/aipyapp" \
            --maintainer "ntbowen <ntbowen@users.noreply.github.com>" \
            --license "Apache-2.0" \
            -C package \
            usr/local/bin/aipy=/usr/local/bin/aipy

      - name: Upload DEB/RPM Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: aipy-packages
          path: |
            *.deb
            *.rpm

      - name: Upload Packages to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.deb
            *.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
